### ISSUE TITLE
About Pose Detection by the Camera of Tello

### ISSUE THREAD

**Issue by Tame7790** [RobertGCNiu/Tello-Gesture-Control#2]
Can you tell me the detailed steps, like after copy the files what should I do? My openpose can't use the tello's video. I can only open the openposeDemo and video.py Individually.

**Comment by RobertGCNiu** [comment]
sorry. I missed your message. Can you please tell me the detailed problems you met?

**Comment by Tame7790** [comment]
![image](https://user-images.githubusercontent.com/43593936/54259426-a792a400-45a0-11e9-81bf-b50dc00ac929.png)
I cannot run the video_effect.py, it always told me these problems. I can run the OpenposeDemo and I also can run the tello's tutorial. Of course, I make sure that I enabled BUILD_PYTHON and this Python script is in the right folder. Can you tell me what should I do? Thanks

**Comment by RobertGCNiu** [comment]
You can first test the program without OpenPose by this [program](https://github.com/RobertGCNiu/UAV-Gesture-Control_Python/blob/master/TelloPy-develop-0.5.0/tellopy/examples/video_effect.py). The OpenPose lib has been modified. I haven't tried the latest version. But I recommend you run the program on Ubuntu instead of Windows. I doubt you haven't installed the OpenPose successfully.

**Comment by Tame7790** [comment]
I can run the program successfully and  I doubt I may need to modify the path of windows. Thanks for your reply.

**Comment by Tame7790** [comment]
I run the program eventually. My error is that I use the wrong version of OpenPose( the right one is 1.4.0) Thanks a lot for your help
